/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package jonathanmv.json_to_parquet.model;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-04-06")
public class FriendsEdge implements org.apache.thrift.TBase<FriendsEdge, FriendsEdge._Fields>, java.io.Serializable, Cloneable, Comparable<FriendsEdge> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FriendsEdge");

  private static final org.apache.thrift.protocol.TField ONE_FIELD_DESC = new org.apache.thrift.protocol.TField("one", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField TWO_FIELD_DESC = new org.apache.thrift.protocol.TField("two", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField TIMESTAMP_FIELD_DESC = new org.apache.thrift.protocol.TField("timestamp", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FriendsEdgeStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FriendsEdgeTupleSchemeFactory());
  }

  public PersonID one; // required
  public PersonID two; // required
  public long timestamp; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ONE((short)1, "one"),
    TWO((short)2, "two"),
    TIMESTAMP((short)3, "timestamp");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ONE
          return ONE;
        case 2: // TWO
          return TWO;
        case 3: // TIMESTAMP
          return TIMESTAMP;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TIMESTAMP_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ONE, new org.apache.thrift.meta_data.FieldMetaData("one", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PersonID.class)));
    tmpMap.put(_Fields.TWO, new org.apache.thrift.meta_data.FieldMetaData("two", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PersonID.class)));
    tmpMap.put(_Fields.TIMESTAMP, new org.apache.thrift.meta_data.FieldMetaData("timestamp", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FriendsEdge.class, metaDataMap);
  }

  public FriendsEdge() {
  }

  public FriendsEdge(
    PersonID one,
    PersonID two,
    long timestamp)
  {
    this();
    this.one = one;
    this.two = two;
    this.timestamp = timestamp;
    setTimestampIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FriendsEdge(FriendsEdge other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetOne()) {
      this.one = new PersonID(other.one);
    }
    if (other.isSetTwo()) {
      this.two = new PersonID(other.two);
    }
    this.timestamp = other.timestamp;
  }

  public FriendsEdge deepCopy() {
    return new FriendsEdge(this);
  }

  @Override
  public void clear() {
    this.one = null;
    this.two = null;
    setTimestampIsSet(false);
    this.timestamp = 0;
  }

  public PersonID getOne() {
    return this.one;
  }

  public FriendsEdge setOne(PersonID one) {
    this.one = one;
    return this;
  }

  public void unsetOne() {
    this.one = null;
  }

  /** Returns true if field one is set (has been assigned a value) and false otherwise */
  public boolean isSetOne() {
    return this.one != null;
  }

  public void setOneIsSet(boolean value) {
    if (!value) {
      this.one = null;
    }
  }

  public PersonID getTwo() {
    return this.two;
  }

  public FriendsEdge setTwo(PersonID two) {
    this.two = two;
    return this;
  }

  public void unsetTwo() {
    this.two = null;
  }

  /** Returns true if field two is set (has been assigned a value) and false otherwise */
  public boolean isSetTwo() {
    return this.two != null;
  }

  public void setTwoIsSet(boolean value) {
    if (!value) {
      this.two = null;
    }
  }

  public long getTimestamp() {
    return this.timestamp;
  }

  public FriendsEdge setTimestamp(long timestamp) {
    this.timestamp = timestamp;
    setTimestampIsSet(true);
    return this;
  }

  public void unsetTimestamp() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  /** Returns true if field timestamp is set (has been assigned a value) and false otherwise */
  public boolean isSetTimestamp() {
    return EncodingUtils.testBit(__isset_bitfield, __TIMESTAMP_ISSET_ID);
  }

  public void setTimestampIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIMESTAMP_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ONE:
      if (value == null) {
        unsetOne();
      } else {
        setOne((PersonID)value);
      }
      break;

    case TWO:
      if (value == null) {
        unsetTwo();
      } else {
        setTwo((PersonID)value);
      }
      break;

    case TIMESTAMP:
      if (value == null) {
        unsetTimestamp();
      } else {
        setTimestamp((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ONE:
      return getOne();

    case TWO:
      return getTwo();

    case TIMESTAMP:
      return getTimestamp();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ONE:
      return isSetOne();
    case TWO:
      return isSetTwo();
    case TIMESTAMP:
      return isSetTimestamp();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FriendsEdge)
      return this.equals((FriendsEdge)that);
    return false;
  }

  public boolean equals(FriendsEdge that) {
    if (that == null)
      return false;

    boolean this_present_one = true && this.isSetOne();
    boolean that_present_one = true && that.isSetOne();
    if (this_present_one || that_present_one) {
      if (!(this_present_one && that_present_one))
        return false;
      if (!this.one.equals(that.one))
        return false;
    }

    boolean this_present_two = true && this.isSetTwo();
    boolean that_present_two = true && that.isSetTwo();
    if (this_present_two || that_present_two) {
      if (!(this_present_two && that_present_two))
        return false;
      if (!this.two.equals(that.two))
        return false;
    }

    boolean this_present_timestamp = true;
    boolean that_present_timestamp = true;
    if (this_present_timestamp || that_present_timestamp) {
      if (!(this_present_timestamp && that_present_timestamp))
        return false;
      if (this.timestamp != that.timestamp)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_one = true && (isSetOne());
    list.add(present_one);
    if (present_one)
      list.add(one);

    boolean present_two = true && (isSetTwo());
    list.add(present_two);
    if (present_two)
      list.add(two);

    boolean present_timestamp = true;
    list.add(present_timestamp);
    if (present_timestamp)
      list.add(timestamp);

    return list.hashCode();
  }

  @Override
  public int compareTo(FriendsEdge other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetOne()).compareTo(other.isSetOne());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOne()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.one, other.one);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTwo()).compareTo(other.isSetTwo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTwo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.two, other.two);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTimestamp()).compareTo(other.isSetTimestamp());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimestamp()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timestamp, other.timestamp);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FriendsEdge(");
    boolean first = true;

    sb.append("one:");
    if (this.one == null) {
      sb.append("null");
    } else {
      sb.append(this.one);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("two:");
    if (this.two == null) {
      sb.append("null");
    } else {
      sb.append(this.two);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("timestamp:");
    sb.append(this.timestamp);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (one == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'one' was not present! Struct: " + toString());
    }
    if (two == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'two' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'timestamp' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FriendsEdgeStandardSchemeFactory implements SchemeFactory {
    public FriendsEdgeStandardScheme getScheme() {
      return new FriendsEdgeStandardScheme();
    }
  }

  private static class FriendsEdgeStandardScheme extends StandardScheme<FriendsEdge> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FriendsEdge struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ONE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.one = new PersonID();
              struct.one.read(iprot);
              struct.setOneIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TWO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.two = new PersonID();
              struct.two.read(iprot);
              struct.setTwoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // TIMESTAMP
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.timestamp = iprot.readI64();
              struct.setTimestampIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetTimestamp()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'timestamp' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FriendsEdge struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.one != null) {
        oprot.writeFieldBegin(ONE_FIELD_DESC);
        struct.one.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.two != null) {
        oprot.writeFieldBegin(TWO_FIELD_DESC);
        struct.two.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TIMESTAMP_FIELD_DESC);
      oprot.writeI64(struct.timestamp);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FriendsEdgeTupleSchemeFactory implements SchemeFactory {
    public FriendsEdgeTupleScheme getScheme() {
      return new FriendsEdgeTupleScheme();
    }
  }

  private static class FriendsEdgeTupleScheme extends TupleScheme<FriendsEdge> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FriendsEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.one.write(oprot);
      struct.two.write(oprot);
      oprot.writeI64(struct.timestamp);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FriendsEdge struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.one = new PersonID();
      struct.one.read(iprot);
      struct.setOneIsSet(true);
      struct.two = new PersonID();
      struct.two.read(iprot);
      struct.setTwoIsSet(true);
      struct.timestamp = iprot.readI64();
      struct.setTimestampIsSet(true);
    }
  }

}

